change to mvn get dependency

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -28,41 +28,43 @@ fi
 configure_proxy
 configure_mirrors
 
-manage_incremental_build
+# manage_incremental_build
 
-# If a pom.xml is present, this is a normal build scenario
-# so run maven.
-if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
-  pushd $LOCAL_SOURCE_DIR &> /dev/null
+echo "grabbing the artifact $ARTIFACT_GROUPID:$ARTIFACT_ARTIFACTID:$ARTIFACT_VERSION:$ARTIFACT_PACKAGING"
+mvn dependency:get -DgroupId="$ARTIFACT_GROUPID" -DartifactId="$ARTIFACT_ARTIFACTID" -Dversion="$ARTIFACT_VERSION" -Dpackaging="$ARTIFACT_PACKAGING" -Ddest="target/"
+# # If a pom.xml is present, this is a normal build scenario
+# # so run maven.
+# if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
+#   pushd $LOCAL_SOURCE_DIR &> /dev/null
 
-  MAVEN_ARGS=${MAVEN_ARGS--e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package}
+#   MAVEN_ARGS=${MAVEN_ARGS--e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package}
 
-  # Always force IPv4 (CLOUD-188)
-  # Append user-supplied arguments (CLOUD-412)
-  MAVEN_ARGS="$MAVEN_ARGS -Djava.net.preferIPv4Stack=true ${MAVEN_ARGS_APPEND}"
+#   # Always force IPv4 (CLOUD-188)
+#   # Append user-supplied arguments (CLOUD-412)
+#   MAVEN_ARGS="$MAVEN_ARGS -Djava.net.preferIPv4Stack=true ${MAVEN_ARGS_APPEND}"
 
-  echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
+#   echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
 
-  echo "Using $(mvn --version)"
+#   echo "Using $(mvn --version)"
 
-  # Execute the actual build
-  mvn $MAVEN_ARGS
+#   # Execute the actual build
+#   mvn $MAVEN_ARGS
 
-  ERR=$?
-  if [ $ERR -ne 0 ]; then
-    echo "Aborting due to error code $ERR from Maven build"
-    exit $ERR
-  fi
+#   ERR=$?
+#   if [ $ERR -ne 0 ]; then
+#     echo "Aborting due to error code $ERR from Maven build"
+#     exit $ERR
+#   fi
 
-  # Copy built artifacts (if any!) from the target/ directory
-  # to the $DEPLOY_DIR directory for later deployment
-  copy_artifacts "$ARTIFACT_DIR" war
+#   # Copy built artifacts (if any!) from the target/ directory
+#   # to the $DEPLOY_DIR directory for later deployment
+#   copy_artifacts "$ARTIFACT_DIR" war
 
-  # optionally clear the local maven repository after the build
-  clear_maven_repository
+#   # optionally clear the local maven repository after the build
+#   clear_maven_repository
 
-  popd &> /dev/null
-fi
+#   popd &> /dev/null
+# fi
 
 # Copy (probably binary) artifacts from the deployments/
 # directory to the $DEPLOY_DIR directory for later deployment
